// Browser acceptance test and real app screen recording; requires Playwright + Chromium.
const {chromium} = require('playwright');
const path = require('path');
const fs = require('fs');

(async () => {
  const root = path.resolve(__dirname, '..');
  const out = path.join(root, 'outputs/acv/browser');
  fs.mkdirSync(out, {recursive:true});
  const browser = await chromium.launch({headless:true});
  const context = await browser.newContext({viewport:{width:1440,height:1000},recordVideo:{dir:out,size:{width:1440,height:1000}},acceptDownloads:true});
  const page = await context.newPage();
  const failures = [];
  page.on('pageerror', e => failures.push(String(e)));
  await page.goto('http://127.0.0.1:8501', {waitUntil:'networkidle'});
  await page.getByText('Find the car that needs attention', {exact:true}).waitFor();
  await page.waitForTimeout(2000);
  await page.locator('input[type=file]').setInputFiles(path.join(root,'PS3/02_Datasets/ACV/Test/acv_test_case.xlsx'));
  await page.waitForTimeout(1500);
  await page.getByRole('button',{name:'Analyze uploaded files',exact:true}).click();
  await page.getByText('First car to inspect', {exact:true}).waitFor({timeout:180000});
  await page.waitForTimeout(4000);
  await page.screenshot({path:path.join(out,'ranking.png'),fullPage:true});
  const csvDownload = page.waitForEvent('download');
  await page.getByRole('button',{name:'Download prediction CSV',exact:true}).click();
  await (await csvDownload).saveAs(path.join(out,'acv_predictions.csv'));
  const zipDownload = page.waitForEvent('download');
  await page.getByRole('button',{name:'Download predictions.zip',exact:true}).click();
  await (await zipDownload).saveAs(path.join(out,'predictions.zip'));
  await page.getByRole('tab',{name:'Cooling evidence',exact:true}).click();
  await page.waitForTimeout(3000);
  await page.screenshot({path:path.join(out,'evidence.png'),fullPage:true});
  await page.mouse.wheel(0,550);
  await page.waitForTimeout(2500);
  await page.mouse.wheel(0,-550);
  await page.getByRole('tab',{name:'Data quality',exact:true}).click();
  await page.waitForTimeout(3000);
  await page.screenshot({path:path.join(out,'quality.png'),fullPage:true});
  await page.getByRole('tab',{name:'Car ranking',exact:true}).click();
  await page.getByRole('button',{name:'Check ranking stability',exact:true}).click();
  await page.getByText(/Frequencies are not fault probabilities/).waitFor({timeout:180000});
  await page.waitForTimeout(2500);
  await page.mouse.wheel(0,650);
  await page.waitForTimeout(3500);
  const errors = await page.locator('[data-testid="stException"]').allTextContents();
  failures.push(...errors);
  const video = page.video();
  await context.close();
  const videoPath = await video.path();
  fs.writeFileSync(path.join(out,'acceptance.json'),JSON.stringify({videoPath,failures,uploaded:'acv_test_case.xlsx',downloads:['acv_predictions.csv','predictions.zip']},null,2));
  await browser.close();
  if (failures.length) throw new Error(failures.join('\n'));
  console.log(videoPath);
})();
